spring:
  main:
    lazy-initialization: true
  application:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver


server:
  port: 8080

jwt:
  secret: ${JWT_SECERT}
  expiration: 86400000
  refresh-expiration: 604800000